#!/usr/bin/env bash

#set -e

# Make migrations
echo "Running migrations"
python3 manage.py migrate
echo "Migrations done"

# #Cities
# echo "Start cities"
# python3 manage.py cities_light
# echo "Finish with cities"

# Make collectstatic
echo "Running collectstatic"
python3 manage.py collectstatic --noinput
echo "collectstatic done"

if [ -n "${DJANGO_SUPERUSER_PASSWORD}" ]; then
    echo "Create superuser"
    python3 manage.py createsuperuser --noinput --username ${DJANGO_SUPERUSER_USERNAME} --email ${DJANGO_SUPERUSER_EMAIL}
    echo "Superuser created"
fi

# Run Project
echo "Running project"
exec uwsgi --socket=:8002 --module=config.wsgi:application --py-autoreload=1 --chdir=/app
echo "Running project done"
